#line 1 "lexer.cc"

#line 3 "lexer.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

    /* The c++ scanner is a mess. The FlexLexer.h header file relies on the
     * following macro. This is required in order to pass the c++-multiple-scanners
     * test in the regression suite. We get reports that it breaks inheritance.
     * We will address this in a future release of flex, or omit the C++ scanner
     * altogether.
     */
    #define yyFlexLexer yyFlexLexer

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */
#include <iostream>
#include <errno.h>
#include <cstdlib>
#include <cstdio>
#include <cstring>
/* end standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{

	std::streambuf* yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

#define yytext_ptr yytext

#include <FlexLexer.h>

inline int yyFlexLexer::yywrap() { return 1; }

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 133
#define YY_END_OF_BUFFER 134
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[366] =
    {   0,
        0,    0,    0,    0,    0,    0,  134,  132,    1,  131,
       94,  113,   57,   85,   95,  132,   73,   74,   83,   81,
       79,   82,   80,   84,   70,   70,   56,  130,   89,  101,
       88,  129,   58,  128,  128,  128,  128,  128,  128,  128,
       75,   76,   96,  127,  127,  127,  127,  127,  127,  127,
      127,  127,  127,  127,  127,  127,  127,  127,  127,  127,
      127,  127,   77,   97,   78,   98,  114,  126,  125,  132,
        6,    6,    6,    6,    1,  129,   87,  106,   92,  109,
        0,    0,  104,  102,  103,   69,    3,    2,  105,    0,
       70,   71,   69,    0,   72,    0,   53,   54,  100,   91,

       86,   52,   55,   90,   99,  128,  128,  128,  128,  128,
      128,  128,  128,  110,  127,  127,  127,   59,  127,  127,
      127,   18,  127,  127,  127,  127,  127,  127,   25,  127,
      127,  127,  127,  127,  127,  127,  127,  127,  127,  127,
      127,  127,  127,  127,  127,  127,  127,  127,  127,  127,
      127,  111,   93,  114,  124,  117,  123,  116,  120,  121,
      115,  119,  118,    0,    5,    4,  112,    0,    0,   69,
        0,    0,    2,    2,   71,    0,    0,   69,   72,    0,
      107,  108,  128,  128,  128,  128,    7,  128,  128,  127,
      127,  127,  127,  127,   17,  127,  127,   61,  127,  127,

      127,   24,  127,  127,  127,  127,  127,  127,   31,  127,
      127,  127,  127,  127,  127,  127,  127,  127,  127,  127,
      127,  127,  127,  127,   45,  127,  127,   47,   48,  127,
      127,  127,  123,    0,    0,    0,    0,   69,   69,   69,
        0,  128,   10,  128,  128,   12,  127,   14,  127,  127,
      127,   19,  127,  127,  127,  127,  127,  127,  127,   28,
      127,  127,   32,  127,  127,   66,  127,  127,  127,  127,
      127,  127,  127,   41,  127,  127,  127,   44,   46,  127,
      127,   50,  127,  123,    0,    0,    0,   69,    0,   11,
      128,  128,  127,   15,   16,  127,  127,   21,   22,  127,

      127,   63,  127,   29,   30,  127,  127,  127,  127,  127,
      127,  127,  127,   40,   42,   43,  127,   68,   49,   51,
        0,    0,    8,    9,  127,  127,  127,  127,  127,  127,
       27,   64,   33,   65,  127,  127,  127,  127,   38,   39,
      127,  122,  127,   60,   20,  127,   23,  127,  127,   35,
       36,  127,  127,   13,  127,   26,   34,  127,  127,   62,
       37,  127,  127,   67,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       21,   21,   21,   21,   21,   22,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       36,   36,   37,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   38,   36,   39,   36,   36,   40,   36,   36,
       41,   42,   43,   44,   45,    1,   46,   47,   48,   49,

       50,   51,   52,   53,   54,   55,   56,   57,   58,   59,
       60,   61,   62,   63,   64,   65,   66,   67,   68,   69,
       70,   71,   72,   73,   74,   75,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[76] =
    {   0,
        1,    1,    2,    3,    4,    3,    5,    3,    3,    6,
        1,    1,    3,    3,    1,    3,    1,    3,    7,    7,
        7,    8,    3,    1,    3,    3,    3,    3,    3,    8,
        8,    8,    8,    8,    8,    5,    5,    5,    5,    5,
        1,    9,    1,    3,   10,    8,    7,    8,    8,    8,
        7,    5,    5,    5,    5,    5,    5,    5,   11,    5,
        5,    5,   11,    5,   11,   11,    5,    5,    5,    5,
        5,    1,    3,    1,    3
    } ;

static const flex_int16_t yy_base[386] =
    {   0,
        0,    0,   73,   74,   77,   78,  884,  885,  881,  885,
      856,  885,    0,  855,   73,  838,  885,  885,  853,  852,
      885,  851,   64,   74,  100,   57,    0,  885,   82,   67,
       83,    0,    0,   66,  831,   79,   58,   68,   78,   69,
      885,  885,  849,  829,   91,   96,   94,  101,  111,  116,
       56,  117,  114,  121,  127,   80,  131,  132,  134,  138,
      133,  146,  885,  126,  885,    0,    0,  885,  885,  200,
      885,  885,  855,  859,  869,    0,    0,    0,    0,    0,
      860,  173,    0,    0,    0,  195,    0,  263,    0,  187,
        0,  191,  885,  234,  824,  204,    0,    0,  842,    0,

        0,    0,    0,    0,  841,  821,  335,  159,  167,  186,
      173,  198,  187,    0,  820,  407,  219,  819,  229,  188,
      217,  818,  233,  250,  192,  144,  225,  237,  817,  240,
      251,  242,  258,   44,  253,  259,  266,  270,  273,  272,
      264,  279,  274,  277,  300,  289,  283,  302,  288,  307,
      323,    0,    0,    0,  885,  885,  335,  885,  885,  885,
      885,  885,  885,    0,  885,  885,  885,  364,    0,  420,
      372,  377,    0,  479,  356,  362,  383,  479,  816,  815,
        0,    0,    0,  344,  324,  213,  814,  355,  361,    0,
      372,  369,  282,  367,  813,  373,  379,  812,  393,  383,

      399,  811,  401,  403,  405,  411,  415,  418,  797,  417,
      422,  333,  312,  423,   92,  444,  419,  428,  434,  465,
      432,  430,  468,  475,  796,  481,  458,  795,  794,  484,
      182,  487,  514,    0,  526,    0,  518,  529,  536,  885,
      546,  473,  793,  515,  514,  790,  516,  789,  530,  518,
      525,  788,  531,  539,  541,  543,  532,  548,  549,  787,
      551,  554,  786,  471,  555,  779,  556,  557,  559,  564,
      561,  565,  567,  767,  568,  573,  571,  764,  762,  575,
      578,  759,  577,  885,    0,  790,    0,  612,  620,  750,
      598,  592,  604,  748,  744,  601,  607,  741,  609,  610,

      608,  737,  614,  734,  727,  615,  617,  623,  624,  625,
      627,  629,  580,  723,  720,  719,  633,  718,  717,  716,
        0,    0,  691,  690,  634,  636,  638,  639,  640,  641,
      689,  688,  687,  686,  642,  647,  651,  644,  684,  683,
      653,  885,  658,  679,  677,  659,  676,  660,  661,  508,
      497,  662,  663,  464,  668,  431,  322,  669,  670,  230,
      228,  671,  672,  151,  885,  737,  748,  757,  766,  773,
      780,  791,  799,  810,  815,  819,  821,  827,  834,  837,
      839,  841,  843,  845,  847
    } ;

static const flex_int16_t yy_def[386] =
    {   0,
      365,    1,  366,  366,  367,  367,  365,  365,  365,  365,
      368,  365,  368,  368,  368,  369,  365,  365,  368,  368,
      365,  368,  365,  368,  365,   25,  368,  365,  368,  368,
      368,  368,  368,  370,  370,  370,  370,  370,  370,  370,
      365,  365,  368,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  365,  368,  365,  368,  372,  365,  365,  365,
      365,  365,  365,  365,  365,  368,  368,  368,  368,  368,
      365,  373,  368,  368,  368,  365,  368,  374,  368,  365,
       26,  365,  365,  365,  375,  365,  368,  368,  368,  368,

      368,  368,  368,  368,  368,  370,  370,  370,  370,  370,
      370,  370,  370,  368,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  368,  368,  372,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  376,  365,  365,  365,  365,  377,  365,
      365,  365,  374,  374,  365,  365,  365,  365,  375,  375,
      368,  368,  378,  370,  370,  370,  370,  370,  370,  379,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,

      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  365,  380,  365,  381,  365,  365,  365,  365,
      365,  370,  370,  370,  370,  370,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  365,  382,  365,  383,  365,  365,  370,
      370,  370,  371,  371,  371,  371,  371,  371,  371,  371,

      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      384,  385,  370,  370,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  365,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,    0,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365
    } ;

static const flex_int16_t yy_nxt[961] =
    {   0,
        8,    9,   10,   11,   12,   13,    8,   14,   15,   16,
       17,   18,   19,   20,   21,   22,   23,   24,   25,   26,
       26,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   35,   35,   35,   38,   39,   40,   35,
       41,   32,   42,   43,   44,   45,   44,   46,   47,   48,
       49,   44,   44,   50,   44,   44,   51,   52,   53,   54,
       55,   44,   56,   57,   58,   59,   60,   61,   44,   62,
       44,   63,   64,   65,   66,   68,   68,   69,   69,   72,
       72,   79,   86,   86,   86,   86,   87,  365,  116,   73,
       73,   88,  101,  102,   74,   74,  365,   97,   80,   89,

      116,  132,  107,  365,   98,  103,   99,  100,  104,  105,
      107,  209,  107,  107,   70,   70,   90,  110,   91,   91,
       91,   91,  107,  107,  116,  365,  111,  113,  108,  141,
       92,  109,   93,   94,   93,  116,  116,  117,  116,   95,
      116,  119,  112,  121,   96,  116,   92,  268,   93,   94,
       93,  152,  120,  122,  118,  116,  126,  123,  116,  124,
      116,  116,  133,  134,  127,  116,  129,  136,   95,  125,
      128,  116,  139,  130,  131,  116,  116,  116,  116,  135,
      142,  137,  116,  148,  144,  149,  150,  138,  116,  140,
      116,  168,  168,  168,  145,  116,  143,  147,  153,  151,

      200,  146,  155,  107,  156,   86,   86,   86,   86,  175,
      175,  107,  185,  170,  170,  170,  170,  107,  157,  157,
      157,  184,   91,   91,   91,   91,  116,   93,  171,   93,
      107,  107,  116,  194,  282,  176,  116,  187,  169,  172,
      189,  158,  107,   93,  171,   93,  159,  177,   96,  177,
      160,  186,  178,  178,  178,  178,  199,  107,  161,  244,
      188,  116,  162,  116,  163,  164,  174,  195,  174,  116,
      174,  174,  116,  116,  116,  174,  174,  116,  174,  196,
      174,  116,  191,  201,  116,  174,  116,  174,  174,  174,
      174,  174,  192,  193,  116,  116,  197,  116,  198,  202,

      203,  204,  116,  116,  174,  207,  174,  205,  116,  210,
      116,  212,  206,  211,  116,  213,  116,  116,  116,  214,
      215,  116,  208,  116,  219,  216,  116,  116,  218,  249,
      221,  217,  116,  116,  220,  174,  227,  174,  183,  222,
      183,  230,  183,  183,  116,  223,  116,  183,  183,  226,
      183,  116,  183,  233,  233,  233,  116,  183,  228,  183,
      183,  183,  183,  183,  229,  224,  116,  116,  107,  225,
      266,  231,  232,  167,  175,  175,  183,  116,  183,  107,
      175,  175,  235,  235,  235,  237,  243,  237,  107,  242,
      238,  238,  238,  238,  265,  170,  170,  170,  170,  107,

      176,  178,  178,  178,  178,  107,  176,  183,  245,  183,
      190,  116,  190,  116,  190,  190,  116,  116,  248,  190,
      190,  172,  190,  116,  190,  246,  251,  116,  252,  190,
      250,  190,  190,  190,  190,  190,  247,  116,  170,  170,
      170,  170,  253,  116,  255,  116,  254,  116,  190,  116,
      190,  116,   93,  171,   93,  116,  258,  256,  259,  116,
      257,  116,  116,  116,  172,  262,  116,  116,   93,  171,
       93,  264,  116,  263,  116,  116,  116,  261,  116,  190,
      260,  190,  174,  270,  174,  267,  174,  174,  116,  275,
      272,  174,  174,  271,  174,  274,  174,  239,  239,  239,

      239,  174,  116,  174,  174,  174,  174,  174,  116,  116,
      269,  240,  116,  240,  273,  116,  280,  107,  306,  116,
      174,  276,  174,  241,  278,  116,  277,  240,  116,  240,
      279,  116,  284,  284,  284,  167,  238,  238,  238,  238,
      281,  116,  290,  283,  286,  286,  286,  288,  288,  288,
      288,  174,  116,  174,  239,  239,  239,  239,  107,  107,
      116,   93,  116,   93,  239,  239,  239,  239,  240,  116,
      240,  291,  292,  289,  116,  116,  116,   93,  293,   93,
      241,  295,  294,  116,  240,  116,  240,  116,  298,  297,
      241,  296,  116,  116,  301,  116,  300,  299,  116,  116,

      116,  116,  309,  116,  310,  116,  305,  303,  116,  116,
      304,  116,  116,  311,  313,  116,  302,  116,  308,  116,
      307,  116,  116,  312,  116,  320,  318,  319,  340,  314,
      288,  288,  288,  288,  317,  315,  107,  316,  288,  288,
      288,  288,  107,  324,   93,  116,   93,  323,  116,  325,
      326,  116,  116,  116,  116,  327,  289,  330,  116,  116,
       93,  116,   93,  332,  289,  329,  334,  116,  116,  116,
      328,  116,  331,  116,  338,  336,  335,  116,  116,  333,
      116,  343,  116,  116,  116,  116,  116,  339,  116,  337,
      349,  116,  346,  341,  348,  116,  350,  116,  353,  344,

      351,  345,  116,  116,  116,  116,  116,  116,  352,  347,
      357,  358,  116,  116,  116,  116,  116,  361,  355,  362,
      116,  116,  354,  116,  356,  359,  360,  116,  116,  363,
      116,  116,  116,  116,  107,  107,  364,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   76,
      116,  116,  116,  116,  116,   76,   81,  116,   81,   81,
       81,  116,   81,   81,   81,   81,   81,  106,  116,  106,
      106,  116,  106,  106,  115,  116,  115,  115,  116,  115,
      115,  154,  116,  154,  107,  154,  154,  154,  154,  167,

      154,  154,   81,  116,   81,   81,  116,   81,  116,   81,
      173,  116,  173,  173,  173,  173,  173,  173,  173,  173,
      173,  179,  179,  116,  179,  234,  234,  236,  236,  183,
      116,  116,  116,  116,  107,  183,  190,  107,  116,  116,
      116,  116,  190,  285,  285,  287,  287,  321,  321,  322,
      322,  342,  342,   81,   81,  116,  116,  116,  107,  180,
      180,  116,  116,  116,  116,  107,  182,  181,  180,  167,
       75,  166,  165,  116,  114,  107,   85,   84,   83,   82,
       78,   77,   75,  365,    7,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,

      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365
    } ;

static const flex_int16_t yy_chk[961] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    4,    3,    4,    5,
        6,   15,   23,   23,   23,   23,   24,   26,  134,    5,
        6,   24,   30,   30,    5,    6,   26,   29,   15,   24,

       51,   51,   37,   26,   29,   31,   29,   29,   31,   31,
       34,  134,   38,   40,    3,    4,   25,   37,   25,   25,
       25,   25,   39,   36,   56,   26,   38,   40,   34,   56,
       25,   36,   25,   25,   25,   45,  215,   45,   47,   25,
       46,   46,   39,   47,   25,   48,   25,  215,   25,   25,
       25,   64,   46,   47,   45,   49,   49,   48,   53,   48,
       50,   52,   52,   53,   49,   54,   50,   54,   25,   48,
       49,   55,   55,   50,   50,   57,   58,   61,   59,   53,
       57,   54,   60,   60,   58,   61,   61,   54,  126,   55,
       62,   82,   82,   82,   58,  364,   57,   59,   64,   62,

      126,   58,   70,  108,   70,   90,   90,   90,   90,   92,
       92,  109,  109,   86,   86,   86,   86,  111,   70,   70,
       70,  108,   96,   96,   96,   96,  231,   86,   86,   86,
      110,  113,  120,  120,  231,   92,  125,  111,   82,   86,
      113,   70,  112,   86,   86,   86,   70,   94,   96,   94,
       70,  110,   94,   94,   94,   94,  125,  186,   70,  186,
      112,  121,   70,  117,   70,   70,   88,  121,   88,  127,
       88,   88,  361,  119,  360,   88,   88,  123,   88,  121,
       88,  128,  117,  127,  130,   88,  132,   88,   88,   88,
       88,   88,  119,  119,  124,  131,  123,  135,  124,  128,

      130,  131,  133,  136,   88,  133,   88,  131,  141,  135,
      137,  137,  132,  136,  138,  137,  140,  139,  143,  138,
      139,  144,  133,  142,  142,  140,  193,  147,  141,  193,
      144,  140,  149,  146,  143,   88,  147,   88,  107,  144,
      107,  149,  107,  107,  145,  145,  148,  107,  107,  146,
      107,  150,  107,  157,  157,  157,  213,  107,  148,  107,
      107,  107,  107,  107,  148,  145,  357,  151,  185,  145,
      213,  150,  151,  168,  175,  175,  107,  212,  107,  107,
      176,  176,  168,  168,  168,  171,  185,  171,  184,  184,
      171,  171,  171,  171,  212,  172,  172,  172,  172,  188,

      175,  177,  177,  177,  177,  189,  176,  107,  188,  107,
      116,  194,  116,  192,  116,  116,  191,  196,  192,  116,
      116,  172,  116,  197,  116,  189,  196,  200,  197,  116,
      194,  116,  116,  116,  116,  116,  191,  199,  170,  170,
      170,  170,  199,  201,  201,  203,  200,  204,  116,  205,
      116,  116,  170,  170,  170,  206,  204,  203,  205,  207,
      203,  210,  208,  217,  170,  208,  211,  214,  170,  170,
      170,  211,  218,  210,  222,  356,  221,  207,  219,  116,
      206,  116,  174,  217,  174,  214,  174,  174,  216,  222,
      219,  174,  174,  218,  174,  221,  174,  178,  178,  178,

      178,  174,  227,  174,  174,  174,  174,  174,  354,  220,
      216,  178,  223,  178,  220,  264,  227,  242,  264,  224,
      174,  223,  174,  178,  224,  226,  223,  178,  230,  178,
      226,  232,  233,  233,  233,  235,  237,  237,  237,  237,
      230,  351,  242,  232,  235,  235,  235,  238,  238,  238,
      238,  174,  350,  174,  239,  239,  239,  239,  245,  244,
      247,  238,  250,  238,  241,  241,  241,  241,  239,  251,
      239,  244,  245,  238,  249,  253,  257,  238,  247,  238,
      239,  250,  249,  254,  239,  255,  239,  256,  254,  253,
      241,  251,  258,  259,  257,  261,  256,  255,  262,  265,

      267,  268,  268,  269,  269,  271,  262,  259,  270,  272,
      261,  273,  275,  270,  272,  277,  258,  276,  267,  280,
      265,  283,  281,  271,  313,  283,  280,  281,  313,  273,
      288,  288,  288,  288,  277,  275,  292,  276,  289,  289,
      289,  289,  291,  292,  288,  296,  288,  291,  293,  293,
      296,  297,  301,  299,  300,  297,  288,  300,  303,  306,
      288,  307,  288,  303,  289,  299,  307,  308,  309,  310,
      297,  311,  301,  312,  311,  309,  308,  317,  325,  306,
      326,  325,  327,  328,  329,  330,  335,  312,  338,  310,
      335,  336,  328,  317,  330,  337,  336,  341,  341,  326,

      337,  327,  343,  346,  348,  349,  352,  353,  338,  329,
      349,  352,  355,  358,  359,  362,  363,  358,  346,  359,
      347,  345,  343,  344,  348,  353,  355,  340,  339,  362,
      334,  333,  332,  331,  324,  323,  363,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  368,
      320,  319,  318,  316,  315,  368,  369,  314,  369,  369,
      369,  305,  369,  369,  369,  369,  369,  370,  304,  370,
      370,  302,  370,  370,  371,  298,  371,  371,  295,  371,
      371,  372,  294,  372,  290,  372,  372,  372,  372,  286,

      372,  372,  373,  282,  373,  373,  279,  373,  278,  373,
      374,  274,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  375,  375,  266,  375,  376,  376,  377,  377,  378,
      263,  260,  252,  248,  246,  378,  379,  243,  229,  228,
      225,  209,  379,  380,  380,  381,  381,  382,  382,  383,
      383,  384,  384,  385,  385,  202,  198,  195,  187,  180,
      179,  129,  122,  118,  115,  106,  105,   99,   95,   81,
       75,   74,   73,   44,   43,   35,   22,   20,   19,   16,
       14,   11,    9,    7,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,

      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "lexer.l"


#line 9 "lexer.l"
    #include <iostream>
    #include <fstream>
    #include <string>
    #include <cstdlib>
    using namespace std;

    void printLiteral(string type, string literal);
    void printType(string type);
    void printKeyword(string keyword);
    void printOperator(string op);
    void printIdentificator(string id);
    void printSeparator(string separator);

    string stripUnderscores(string s);
    string stripSuffix(string s, string chars);
    string normalizeInt(string s);
    string normalizeBinInt(string s);
    string normalizeHexInt(string s);
    string normalizeDouble(string s);

    string normalizeChar(string s);
    string decodeChar(string s);

#line 757 "lexer.cc"
/* хвост имени */
/* variable */
/*constructor identifier (класс, объект, тип) */
#line 761 "lexer.cc"

#define INITIAL 0
#define STRING 1
#define ML_COMMENT 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
#define ECHO LexerOutput( yytext, yyleng )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
\
	if ( (int)(result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) LexerError( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
#define YY_DECL int yyFlexLexer::yylex()
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin.rdbuf(std::cin.rdbuf());

		if ( ! yyout )
			yyout.rdbuf(std::cout.rdbuf());

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 68 "lexer.l"



#line 72 "lexer.l"
    string stringBuffer = "";
    int mlCommentDepth = 0;


#line 904 "lexer.cc"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 366 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 365 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 76 "lexer.l"
{ /* пропуск пробелов */ }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 78 "lexer.l"
{ /* пропуск однострочных комментариев */ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 80 "lexer.l"
{ mlCommentDepth = 1; BEGIN(ML_COMMENT); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 81 "lexer.l"
{ mlCommentDepth++; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 82 "lexer.l"
{ if (--mlCommentDepth == 0) BEGIN(INITIAL); }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 83 "lexer.l"
{ /* пропускаем перевод строки и символы внутри комментария */ }
	YY_BREAK
case YY_STATE_EOF(ML_COMMENT):
#line 84 "lexer.l"
{ cerr << "ERROR: unterminated multi-line comment" << endl;
                       BEGIN(INITIAL); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 87 "lexer.l"
{ printType(YYText()); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 88 "lexer.l"
{ printType(YYText()); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 89 "lexer.l"
{ printType(YYText()); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 90 "lexer.l"
{ printType(YYText()); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 91 "lexer.l"
{ printType(YYText()); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 92 "lexer.l"
{ printType(YYText()); } /* аналог void */
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 94 "lexer.l"
{ printKeyword(YYText()); } /* Regular keywords */
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 95 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 96 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 97 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 98 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 99 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 100 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 101 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 102 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 103 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 104 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 105 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 106 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 107 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 108 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 109 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 110 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 111 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 112 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 113 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 114 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 115 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 116 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 117 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 118 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 119 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 120 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 121 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 122 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 123 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 124 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 125 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 126 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 127 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 128 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 129 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 130 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 131 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 132 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 134 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 135 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 136 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 137 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 138 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 139 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 140 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 142 "lexer.l"
{ printKeyword(YYText()); } /* Soft keywords */
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 143 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 144 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 145 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 146 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 147 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 148 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 149 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 150 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 151 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 153 "lexer.l"
{ printLiteral("double", normalizeDouble(YYText())); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 155 "lexer.l"
{ printLiteral("int", normalizeInt(YYText())); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 156 "lexer.l"
{ printLiteral("int", normalizeBinInt(YYText())); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 157 "lexer.l"
{ printLiteral("int", normalizeHexInt(YYText())); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 159 "lexer.l"
{ printSeparator(YYText()); } /* Разделители */
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 160 "lexer.l"
{ printSeparator(YYText()); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 161 "lexer.l"
{ printSeparator(YYText()); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 162 "lexer.l"
{ printSeparator(YYText()); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 163 "lexer.l"
{ printSeparator(YYText()); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 164 "lexer.l"
{ printSeparator(YYText()); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 165 "lexer.l"
{ printSeparator(YYText()); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 166 "lexer.l"
{ printSeparator(YYText()); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 168 "lexer.l"
{ printOperator(YYText()); } /* Операторы */
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 169 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 170 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 171 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 172 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 174 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 175 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 176 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 177 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 178 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 179 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 181 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 182 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 183 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 185 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 186 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 187 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 188 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 189 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 190 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 192 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 193 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 194 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 195 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 196 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 197 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 198 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 199 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 200 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 201 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 202 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 204 "lexer.l"
{ printLiteral("char", normalizeChar(YYText())); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 206 "lexer.l"
{ stringBuffer = ""; BEGIN(STRING); }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 207 "lexer.l"
{ stringBuffer += YYText(); }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 208 "lexer.l"
{ stringBuffer += '\n'; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 209 "lexer.l"
{ stringBuffer += '\\'; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 210 "lexer.l"
{ stringBuffer += '"'; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 212 "lexer.l"
{ stringBuffer += '\t'; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 213 "lexer.l"
{ stringBuffer += '\r'; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 214 "lexer.l"
{ stringBuffer += '\b'; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 215 "lexer.l"
{ stringBuffer += '\f'; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 217 "lexer.l"
{stringBuffer += decodeChar(YYText());}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 218 "lexer.l"
{stringBuffer += decodeChar(YYText());}
	YY_BREAK
case 124:
/* rule 124 can match eol */
YY_RULE_SETUP
#line 220 "lexer.l"
{  }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 222 "lexer.l"
{ printLiteral("string", stringBuffer);
                       BEGIN(INITIAL); }
	YY_BREAK
case 126:
/* rule 126 can match eol */
YY_RULE_SETUP
#line 225 "lexer.l"
{ cerr << "ERROR: EOL in string" << endl;
                       BEGIN(INITIAL); }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 228 "lexer.l"
{ printIdentificator(YYText()); }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 229 "lexer.l"
{ printIdentificator(YYText()); }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 230 "lexer.l"
{ printIdentificator(YYText()); }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 232 "lexer.l"
{ printSeparator(YYText()); }
	YY_BREAK
case 131:
/* rule 131 can match eol */
YY_RULE_SETUP
#line 233 "lexer.l"
{ printSeparator("NEW LINE"); }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 235 "lexer.l"
{ cerr << "Unexpected char \'" << YYText()[0] << "\'" << endl; BEGIN(INITIAL);}
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 237 "lexer.l"
ECHO;
	YY_BREAK
#line 1633 "lexer.cc"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STRING):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin.rdbuf();
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* The contents of this function are C++ specific, so the () macro is not used.
 * This constructor simply maintains backward compatibility.
 * DEPRECATED
 */
yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout ):
	yyin(arg_yyin ? arg_yyin->rdbuf() : std::cin.rdbuf()),
	yyout(arg_yyout ? arg_yyout->rdbuf() : std::cout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::yyFlexLexer( std::istream& arg_yyin, std::ostream& arg_yyout ):
	yyin(arg_yyin.rdbuf()),
	yyout(arg_yyout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::ctor_common()
{
	yy_c_buf_p = 0;
	yy_init = 0;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = NULL;

	yy_buffer_stack = NULL;
	yy_buffer_stack_top = 0;
	yy_buffer_stack_max = 0;

	yy_state_buf = 0;

}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::~yyFlexLexer()
{
	delete [] yy_state_buf;
	yyfree( yy_start_stack  );
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yyfree( yy_buffer_stack  );
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream& new_in, std::ostream& new_out )
{
	// was if( new_in )
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE  ) );

	// was if( new_out )
	yyout.rdbuf(new_out.rdbuf());
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream* new_in, std::ostream* new_out )
{
	if( ! new_in ) {
		new_in = &yyin;
	}

	if ( ! new_out ) {
		new_out = &yyout;
	}

	switch_streams(*new_in, *new_out);
}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
{
	if ( yyin.eof() || yyin.fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin.get( buf[0] );

	if ( yyin.eof() )
		return 0;

	if ( yyin.bad() )
		return -1;

	return 1;

#else
	(void) yyin.read( buf, max_size );

	if ( yyin.bad() )
		return -1;
	else
		return yyin.gcount();
#endif
}

void yyFlexLexer::LexerOutput( const char* buf, int size )
{
	(void) yyout.write( buf, size );
}

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
int yyFlexLexer::yy_get_next_buffer()
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    yy_state_type yyFlexLexer::yy_get_previous_state()
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 366 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 366 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 365);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT
    void yyFlexLexer::yyunput( int c, char* yy_bp)
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
#endif

    int yyFlexLexer::yyinput()
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyFlexLexer::yyrestart( std::istream& input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Delegate to the new version that takes an istream reference.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
void yyFlexLexer::yyrestart( std::istream* input_file )
{
	if( ! input_file ) {
		input_file = &yyin;
	}
	yyrestart( *input_file );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

    void yyFlexLexer::yy_load_buffer_state()
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin.rdbuf(YY_CURRENT_BUFFER_LVALUE->yy_input_file);
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream& file, int size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Delegate creation of buffers to the new version that takes an istream reference.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
	YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream* file, int size )
{
	return yy_create_buffer( *file, size );
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, std::istream& file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file.rdbuf();
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

	b->yy_is_interactive = 0;
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yyFlexLexer::yypush_buffer_state (YY_BUFFER_STATE new_buffer)
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yyFlexLexer::yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
void yyFlexLexer::yyensure_buffer_stack(void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

    void yyFlexLexer::yy_push_state( int _new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_size_t) (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc( new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc(
					(void *) (yy_start_stack), new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(_new_state);
}

    void yyFlexLexer::yy_pop_state()
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    int yyFlexLexer::yy_top_state()
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

void yyFlexLexer::LexerError( const char* msg )
{
    	std::cerr << msg << std::endl;
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 237 "lexer.l"


int main(int argc, char** argv) {
    if (argc < 2) {
        cerr << "Usage: " << argv[0] << " <file.scala>" << endl;
        return 1;
    }

    ifstream in(argv[1]);
    if (!in) {
        cerr << "Cannot open file: " << argv[1] << endl;
        return 1;
    }

    yyFlexLexer lexer(&in, &cout);
    lexer.yylex();

    return 0;
}

void printLiteral(string type, string literal) {
    cout << type << " literal: " << literal << endl;
}

void printType(string type) {
    cout << "type: " << type << endl;
}

void printKeyword(string keyword) {
    cout << "keyword: " << keyword << endl;
}

void printOperator(string op) {
    cout << "operator: " << op << endl;
}

void printIdentificator(string id) {
    cout << "id: " << id << endl;
}

void printSeparator(string separator) {
    cout << "separator: " << separator << endl;
}

string stripUnderscores(string s) {
    string result;
    result.reserve(s.size());
    for (char c : s) {
        if (c != '_') result += c;
    }
    return result;
}

string stripSuffix(string s, string chars) {
    if (s.empty()) return s;

    char last = s[s.size() - 1];
    for (char c : chars) {
        if (c == last) return s.substr(0, s.size() - 1);
    }
    return s;
}

string normalizeInt(string s) {
    string result = stripUnderscores(s);
    result = stripSuffix(result, "lL");

    int i = 0;
    while (i + 1 < (int)result.size() && result[i] == '0') i++;
    return result.substr(i);
}

string normalizeBinInt(string s) {
    string clean = stripUnderscores(s);

    bool isLong = false;
    if (!clean.empty()
        && (clean[clean.size() - 1] == 'l' || clean[clean.size() - 1] == 'L')) {
        clean = clean.substr(0, clean.size() - 1);
        isLong = true;
    }

    int start = 0;
    if (clean.size() >= 2
        && clean[0] == '0'
        && (clean[1] == 'b' || clean[1] == 'B')) {
        start = 2;
    }

    unsigned long long v = 0;
    for (int i = start; i < (int)clean.size(); i++) {
        char c = clean[i];
        if (c == '0' || c == '1') {
            v = (v << 1) | (unsigned long long)(c - '0');
        }
    }

    string result = to_string(v);
    if (isLong) result += "L";
    return result;
}

string normalizeHexInt(string s) {
    string clean = stripUnderscores(s);

    bool isLong = false;
    if (!clean.empty()
        && (clean[clean.size() - 1] == 'l' || clean[clean.size() - 1] == 'L')) {
        clean = clean.substr(0, clean.size() - 1);
        isLong = true;
    }

    int start = 0;
    if (clean.size() >= 2
        && clean[0] == '0'
        && (clean[1] == 'x' || clean[1] == 'X')) {
        start = 2;
    }

    unsigned long long v = 0;
    for (int i = start; i < (int)clean.size(); i++) {
        char c = clean[i];
        int d = -1;
        if (c >= '0' && c <= '9')      d = c - '0';
        else if (c >= 'a' && c <= 'f') d = c - 'a' + 10;
        else if (c >= 'A' && c <= 'F') d = c - 'A' + 10;
        if (d >= 0) v = v * 16 + (unsigned long long)d;
    }

    string result = to_string(v);
    if (isLong) result += "L";

    return result;
}

string normalizeDouble(string s) {
    string result = stripUnderscores(s);
    result = stripSuffix(result, "fFdD");

    if (!result.empty() && result[0] == '.') {
        return "0" + result;
    }

    bool hasDotOrExp = false;
    for (char c : result) {
        if (c == '.' || c == 'e' || c == 'E') {
            hasDotOrExp = true;
            break;
        }
    }

    if (!hasDotOrExp) result += ".0";

    return result;
}

string normalizeChar(string s) {
    // отрезаем обрамляющие '
    string inner = s.substr(1, s.size() - 2);

    return decodeChar(inner);
}

string decodeChar(string inner) {
    // одиночный символ — как есть
    if (inner.size() == 1) return inner;

    // \uXXXX -> попытаемся раскрыть, если печатаемый
    if (inner.size() == 6 && inner[0] == '\\' && inner[1] == 'u') {
        unsigned int code = 0;
        for (int i = 2; i < 6; i++) {
            char c = inner[i];
            int d = -1;
            if (c >= '0' && c <= '9')      d = c - '0';
            else if (c >= 'a' && c <= 'f') d = c - 'a' + 10;
            else if (c >= 'A' && c <= 'F') d = c - 'A' + 10;
            if (d < 0) return inner;
            code = code * 16 + d;
        }
        if (code >= 32 && code < 127 && code != '\'' && code != '\\') {
            return string(1, (char)code);
        }
        return inner;
    }

    // \NNN — восьмеричный escape
    if (inner.size() >= 2 && inner[0] == '\\'
        && inner[1] >= '0' && inner[1] <= '7') {
        unsigned int code = 0;
        int digits = 0;
        for (int i = 1; i < (int)inner.size() && digits < 3; i++) {
            char c = inner[i];
            if (c < '0' || c > '7') break;
            code = code * 8 + (c - '0');
            digits++;
        }
        if (code >= 32 && code < 127 && code != '\'' && code != '\\') {
            return string(1, (char)code);
        }
        return inner;   // непечатаемый — оставляем \NNN
    }

    // остальные escape (\n, \t, \', \\ и т.п.) — как есть
    return inner;
}
