#line 1 "lexer.cc"

#line 3 "lexer.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

    /* The c++ scanner is a mess. The FlexLexer.h header file relies on the
     * following macro. This is required in order to pass the c++-multiple-scanners
     * test in the regression suite. We get reports that it breaks inheritance.
     * We will address this in a future release of flex, or omit the C++ scanner
     * altogether.
     */
    #define yyFlexLexer yyFlexLexer

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */
#include <iostream>
#include <errno.h>
#include <cstdlib>
#include <cstdio>
#include <cstring>
/* end standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{

	std::streambuf* yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

#define yytext_ptr yytext

#include <FlexLexer.h>

inline int yyFlexLexer::yywrap() { return 1; }

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 122
#define YY_END_OF_BUFFER 123
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[367] =
    {   0,
        0,    0,    0,    0,  123,  121,    1,    1,  121,  107,
       57,   89,  121,  121,   76,   77,   87,   85,   82,   86,
       84,   88,   70,   70,   56,   83,   93,   96,   92,  121,
       58,   75,   75,   75,   75,   75,   75,   75,   78,   79,
      121,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   80,  121,   81,  108,  120,  119,  121,    1,   91,
      101,  104,    0,    0,   99,   97,   98,   69,    0,    2,
      100,    0,   70,   71,   69,    0,   72,    0,   53,   54,
        0,   95,   90,   52,   55,   94,    0,    0,   75,   75,

       75,   75,   75,   75,   75,   75,  105,   74,   74,   74,
       59,   74,   74,   74,   14,   74,   74,   74,   74,   74,
       74,   74,   24,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,  106,  108,  118,  111,  117,
      110,  114,  115,  109,  113,  112,    0,   73,    0,    0,
       69,    0,    0,    0,    0,    2,   71,    0,    0,   69,
       72,    0,  102,   51,  103,   50,   75,   75,   75,   75,
        3,   75,   75,   74,   74,   74,   74,   74,   13,   74,
       74,   61,   74,   74,   74,   74,   74,   22,   74,   74,

       74,   74,   74,   74,   29,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       43,   74,   74,   45,   46,   74,   74,   74,  117,    0,
        0,    0,    0,   69,    2,   69,   69,    0,   75,    6,
       75,   75,    8,   74,   10,   74,   74,   74,   15,   16,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   27,
       74,   30,   74,   74,   66,   74,   74,   74,   74,   74,
       74,   74,   39,   74,   74,   74,   42,   44,   74,   74,
       48,   74,  117,    0,    0,    0,   69,    0,    7,   75,
       75,   74,   11,   12,   74,   74,   74,   19,   20,   23,

       74,   74,   63,   74,   28,   74,   74,   74,   74,   74,
       74,   74,   74,   38,   40,   41,   74,   68,   47,   49,
        0,    0,    4,    5,   74,   74,   17,   74,   74,   74,
       74,   26,   64,   31,   65,   74,   74,   74,   74,   36,
       37,   74,  116,   74,   60,   18,   74,   21,   74,   74,
       33,   34,   74,   74,    9,   74,   25,   32,   74,   74,
       62,   35,   74,   74,   67,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       21,   21,   21,   21,   21,   22,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       36,   36,   37,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   38,   36,   39,   36,   36,   40,   36,   36,
       41,   42,   43,   44,   45,    1,   46,   47,   48,   49,

       50,   51,   52,   53,   54,   55,   56,   57,   58,   59,
       60,   61,   62,   63,   64,   65,   66,   67,   68,   69,
       70,   71,   72,   73,   74,   75,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[76] =
    {   0,
        1,    1,    2,    3,    4,    3,    5,    3,    3,    6,
        1,    1,    3,    3,    1,    3,    1,    3,    7,    7,
        7,    8,    3,    1,    3,    3,    3,    3,    3,    8,
        8,    8,    8,    8,    8,    5,    5,    5,    5,    5,
        1,    9,    1,    3,   10,    8,    7,    8,    8,    8,
        7,    5,    5,    5,    5,    5,    5,    5,   11,    5,
        5,    5,   11,    5,   11,   11,    5,    5,    5,    5,
        5,    1,    3,    1,    3
    } ;

static const flex_int16_t yy_base[386] =
    {   0,
        0,    0,   73,   74,  862,  863,   78,   80,  835,  863,
      863,  834,  833,  816,  863,  863,  831,  830,  863,  829,
       65,   75,  100,   58,  863,  863,   74,   65,   80,  828,
      863,   49,  808,   51,   50,   64,   63,   66,  863,  863,
      826,  806,   79,   84,   92,   87,  108,   94,  112,   68,
      113,  110,  119,  127,  129,  132,  122,  120,  142,  146,
      148,  863,  824,  863,    0,  863,  863,  200,  192,  863,
      863,  863,  839,  187,  863,  863,  863,  190,  835,    0,
      863,  194,    0,  177,  863,  212,  802,  224,  863,  863,
      820,  863,  863,  818,  863,  863,  818,  816,  797,  266,

       73,  172,  138,  116,  185,  182,  863,  796,  338,  192,
      795,  193,  204,  210,  794,  207,  215,  222,  144,  209,
      233,  231,  793,  240,  252,  217,  241,  232,  245,  259,
      267,  270,  271,  273,  260,  276,  262,  285,  283,  279,
      289,  305,  291,  292,  281,  863,    0,  863,  863,  339,
      863,  863,  863,  863,  863,  863,    0,  863,  365,    0,
      357,  379,  351,  824,  356,    0,  369,  384,  396,  400,
      791,  790,  863,  863,  863,  863,    0,  364,  342,  378,
      789,  382,  367,    0,  379,  381,  349,  383,  788,  385,
      392,  787,  395,  396,  393,  401,  409,  786,  407,  403,

      405,  413,  416,  421,  785,  417,  423,  293,  419,  425,
      426,  427,  430,  431,  432,  434,  440,  436,  446,  442,
      784,  448,  445,  783,  782,  456,  457,  458,  487,    0,
      499,    0,  502,  506,  863,  511,  863,  516,  472,  781,
      495,  484,  780,  471,  779,  500,  502,  503,  778,  777,
      504,  505,  509,  518,  513,  520,  523,  524,  526,  776,
      528,  775,  435,  531,  761,  532,  466,  533,  537,  535,
      538,  539,  760,  544,  545,  547,  759,  758,  549,  546,
      757,  554,  863,    0,  789,    0,  585,  594,  753,  572,
      574,  563,  752,  751,  578,  576,  580,  750,  586,  743,

      579,  587,  731,  588,  717,  590,  592,  595,  601,  600,
      602,  603,  609,  715,  712,  708,  606,  703,  701,  697,
        0,    0,  694,  690,  611,  612,  687,  615,  616,  618,
      619,  680,  676,  662,  659,  623,  621,  624,  630,  658,
      654,  632,  863,  635,  653,  555,  636,  469,  637,  639,
      389,  336,  640,  638,  287,  646,  254,  184,  648,  642,
      133,   93,  649,  641,   57,  863,  708,  719,  726,  733,
      744,  752,  763,  774,  779,  783,  785,  791,  798,  801,
      803,  805,  807,  809,  811
    } ;

static const flex_int16_t yy_def[386] =
    {   0,
      366,    1,  367,  367,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  368,  366,  366,  366,  366,  366,  366,
      366,  366,  366,   23,  366,  366,  366,  366,  366,  366,
      366,  369,  369,  369,  369,  369,  369,  369,  366,  366,
      366,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  366,  366,  366,  371,  366,  366,  366,  366,  366,
      366,  366,  366,  372,  366,  366,  366,  366,  373,  374,
      366,  366,   24,  366,  366,  366,  375,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  369,  369,

      369,  369,  369,  369,  369,  369,  366,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  366,  371,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  376,  366,  366,  377,
      366,  366,  366,  373,  373,  374,  366,  366,  366,  366,
      375,  375,  366,  366,  366,  366,  378,  369,  369,  369,
      369,  369,  369,  379,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,

      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  366,  380,
      366,  381,  366,  366,  366,  366,  366,  366,  369,  369,
      369,  369,  369,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  366,  382,  366,  383,  366,  366,  369,  369,
      369,  370,  370,  370,  370,  370,  370,  370,  370,  370,

      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      384,  385,  369,  369,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  366,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,    0,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366
    } ;

static const flex_int16_t yy_nxt[939] =
    {   0,
        6,    7,    8,    9,   10,   11,    6,   12,   13,   14,
       15,   16,   17,   18,   19,   20,   21,   22,   23,   24,
       24,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   33,   33,   33,   36,   37,   38,   33,
       39,    6,   40,   41,   42,   43,   42,   44,   45,   46,
       47,   48,   42,   49,   42,   42,   50,   51,   52,   53,
       54,   42,   55,   56,   57,   58,   59,   60,   42,   61,
       42,   62,   63,   64,    6,   66,   66,   67,   67,   69,
       69,   69,   69,   78,   78,   78,   78,   79,  366,   89,
       93,   94,   80,  100,  100,  100,   90,  366,   91,   92,

       81,  109,   95,  102,  366,   96,   97,  100,  100,  103,
      100,  101,  109,  126,   68,   68,   82,  100,   83,   83,
       83,   83,  104,  109,  106,  110,  366,  105,  109,  112,
       84,  109,   85,   86,   85,  178,  109,  109,  109,   87,
      113,  114,  111,  116,   88,  117,   84,  122,   85,   86,
       85,  115,  109,  119,  109,  118,  109,  109,  127,  128,
      100,  120,  123,  109,  109,  130,  109,  121,   87,  124,
      125,  109,  133,  109,  138,  129,  109,  109,  135,  131,
      181,  136,  100,  141,  139,  132,  109,  142,  109,  134,
      109,  140,  109,   69,   69,  167,  167,  137,  143,  144,

      196,  145,  148,  180,  149,  159,  159,  159,  161,  161,
      161,  161,   78,   78,   78,   78,  100,  179,  150,  150,
      150,  168,   85,  162,   85,  169,  100,  169,  109,  100,
      170,  170,  170,  170,  163,  183,  109,  109,   85,  162,
       85,  151,   83,   83,   83,   83,  152,  182,  109,  188,
      153,  109,  160,  109,  109,  185,  186,  187,  154,  109,
      189,  109,  155,  192,  156,  157,  109,  197,   88,  177,
      191,  177,  190,  177,  177,  109,  109,  109,  177,  177,
      193,  177,  194,  177,  109,  109,  195,  203,  177,  109,
      177,  177,  177,  177,  177,  198,  109,  199,  109,  205,

      200,  206,  201,  109,  109,  204,  109,  177,  202,  177,
      100,  109,  208,  207,  109,  109,  209,  109,  211,  210,
      109,  215,  216,  109,  214,  109,  212,  109,  219,  109,
      228,  109,  213,  109,  217,  109,  109,  109,  177,  222,
      177,  184,  223,  184,  226,  184,  184,  218,  220,  109,
      184,  184,  221,  184,  264,  184,  227,  229,  229,  229,
      184,  224,  184,  184,  184,  184,  184,  225,  165,  161,
      161,  161,  161,  235,  158,  161,  161,  161,  161,  184,
      109,  184,  109,  231,  231,  231,  100,  167,  167,   85,
      162,   85,  233,  109,  233,  163,  246,  234,  234,  234,

      234,  163,  167,  167,  240,   85,  162,   85,  100,  239,
      184,  100,  184,  168,  170,  170,  170,  170,  236,  236,
      236,  236,  100,  109,  241,  109,  100,  109,  168,  109,
      245,  243,  237,  109,  237,  242,  109,  109,  248,  109,
      109,  249,  252,  244,  238,  109,  247,  109,  237,  109,
      237,  109,  250,  109,  254,  251,  255,  109,  258,  256,
      109,  109,  257,  109,  253,  109,  259,  109,  261,  109,
      109,  109,  263,  262,  109,  109,  109,  265,  109,  109,
      109,  267,  306,  272,  109,  260,  109,  266,  271,  109,
      109,  277,  109,  268,  269,  274,  270,  278,  273,  275,

      109,  109,  109,  279,  276,  283,  283,  283,  158,  281,
      109,  309,  280,  109,  282,  109,  100,  285,  285,  285,
      234,  234,  234,  234,  287,  287,  287,  287,  100,  236,
      236,  236,  236,  292,  236,  236,  236,  236,   85,  100,
       85,  289,  291,  237,  109,  237,  109,  109,  109,  109,
      288,  290,  293,  109,   85,  238,   85,  109,  298,  237,
      238,  237,  109,  297,  109,  294,  296,  109,  109,  295,
      109,  300,  109,  301,  299,  109,  109,  109,  310,  109,
      305,  109,  109,  109,  304,  302,  311,  313,  109,  109,
      109,  109,  303,  109,  308,  319,  307,  312,  109,  109,

      318,  314,  320,  287,  287,  287,  287,  109,  325,  316,
      317,  315,  287,  287,  287,  287,  100,   85,  100,   85,
      109,  323,  109,  109,  109,  324,  331,  326,  328,  288,
      109,  109,  109,   85,  109,   85,  109,  333,  288,  109,
      327,  335,  330,  329,  109,  109,  109,  109,  336,  339,
      109,  332,  337,  109,  334,  109,  109,  341,  344,  109,
      109,  340,  109,  109,  338,  109,  342,  109,  109,  347,
      351,  350,  349,  352,  109,  345,  109,  354,  346,  109,
      109,  109,  109,  109,  109,  109,  109,  348,  358,  359,
      109,  363,  109,  109,  353,  356,  362,  109,  109,  355,

      360,  357,  109,  109,  361,  365,  109,  364,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   73,
      109,   73,   73,   73,  109,   73,   73,   73,   73,   73,
       99,  109,   99,   99,  100,   99,   99,  108,  100,  108,
      108,  109,  108,  108,  147,  109,  147,  109,  147,  147,
      147,  147,  109,  147,  147,   73,  109,   73,   73,  109,
       73,  109,   73,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  166,  109,  166,  166,  166,  166,
      166,  166,  166,  166,  166,  171,  171,  109,  171,  230,
      230,  232,  232,  177,  109,  109,  109,  100,  158,  177,

      184,  109,  109,  109,  109,  109,  184,  284,  284,  286,
      286,  321,  321,  322,  322,  343,  343,   73,   73,  109,
      109,  109,  109,  109,  100,  100,  109,  109,  109,  109,
      109,  109,  109,  100,  172,  172,  165,  109,  109,  109,
      109,  100,  176,  175,  174,  173,  172,  165,  158,  146,
      109,  107,  100,   98,   77,   76,   75,   74,   72,   71,
       70,  366,    5,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,

      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366
    } ;

static const flex_int16_t yy_chk[939] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    4,    3,    4,    7,
        7,    8,    8,   21,   21,   21,   21,   22,   24,   27,
       28,   28,   22,   32,   35,   34,   27,   24,   27,   27,

       22,  365,   29,   34,   24,   29,   29,   37,   36,   35,
       38,   32,   50,   50,    3,    4,   23,  101,   23,   23,
       23,   23,   36,   43,   38,   43,   24,   37,   44,   44,
       23,   46,   23,   23,   23,  101,   45,  362,   48,   23,
       44,   45,   43,   46,   23,   46,   23,   48,   23,   23,
       23,   45,   47,   47,   52,   46,   49,   51,   51,   52,
      104,   47,   49,   53,   58,   53,   57,   47,   23,   49,
       49,   54,   54,   55,   57,   52,   56,  361,   55,   53,
      104,   56,  103,   58,   57,   53,   59,   59,  119,   54,
       60,   57,   61,   69,   69,   84,   84,   56,   60,   60,

      119,   61,   68,  103,   68,   74,   74,   74,   78,   78,
       78,   78,   82,   82,   82,   82,  102,  102,   68,   68,
       68,   84,   78,   78,   78,   86,  106,   86,  358,  105,
       86,   86,   86,   86,   78,  106,  110,  112,   78,   78,
       78,   68,   88,   88,   88,   88,   68,  105,  113,  113,
       68,  116,   74,  120,  114,  110,  112,  112,   68,  117,
      114,  126,   68,  117,   68,   68,  118,  120,   88,  100,
      116,  100,  114,  100,  100,  122,  128,  121,  100,  100,
      117,  100,  118,  100,  124,  127,  118,  126,  100,  129,
      100,  100,  100,  100,  100,  121,  125,  122,  357,  128,

      124,  129,  125,  130,  135,  127,  137,  100,  125,  100,
      100,  131,  131,  130,  132,  133,  131,  134,  133,  132,
      136,  136,  137,  140,  135,  145,  134,  139,  139,  138,
      145,  355,  134,  141,  138,  143,  144,  208,  100,  140,
      100,  109,  141,  109,  143,  109,  109,  138,  139,  142,
      109,  109,  139,  109,  208,  109,  144,  150,  150,  150,
      109,  142,  109,  109,  109,  109,  109,  142,  165,  163,
      163,  163,  163,  165,  159,  161,  161,  161,  161,  109,
      352,  109,  109,  159,  159,  159,  179,  167,  167,  161,
      161,  161,  162,  187,  162,  163,  187,  162,  162,  162,

      162,  161,  168,  168,  179,  161,  161,  161,  178,  178,
      109,  183,  109,  167,  169,  169,  169,  169,  170,  170,
      170,  170,  180,  185,  180,  186,  182,  188,  168,  190,
      186,  183,  170,  351,  170,  182,  191,  195,  190,  193,
      194,  191,  195,  185,  170,  196,  188,  200,  170,  201,
      170,  199,  193,  197,  197,  194,  199,  202,  201,  200,
      203,  206,  200,  209,  196,  204,  202,  207,  204,  210,
      211,  212,  207,  206,  213,  214,  215,  209,  216,  263,
      218,  211,  263,  216,  217,  203,  220,  210,  215,  223,
      219,  220,  222,  212,  213,  218,  214,  222,  217,  219,

      226,  227,  228,  223,  219,  229,  229,  229,  231,  227,
      267,  267,  226,  348,  228,  244,  239,  231,  231,  231,
      233,  233,  233,  233,  234,  234,  234,  234,  242,  236,
      236,  236,  236,  244,  238,  238,  238,  238,  234,  241,
      234,  239,  242,  236,  246,  236,  247,  248,  251,  252,
      234,  241,  246,  253,  234,  236,  234,  255,  253,  236,
      238,  236,  254,  252,  256,  247,  251,  257,  258,  248,
      259,  255,  261,  256,  254,  264,  266,  268,  268,  270,
      261,  269,  271,  272,  259,  257,  269,  271,  274,  275,
      280,  276,  258,  279,  266,  280,  264,  270,  282,  346,

      279,  272,  282,  287,  287,  287,  287,  292,  292,  275,
      276,  274,  288,  288,  288,  288,  290,  287,  291,  287,
      296,  290,  295,  301,  297,  291,  301,  295,  297,  287,
      299,  302,  304,  287,  306,  287,  307,  304,  288,  308,
      296,  307,  299,  297,  310,  309,  311,  312,  308,  311,
      317,  302,  309,  313,  306,  325,  326,  313,  325,  328,
      329,  312,  330,  331,  310,  337,  317,  336,  338,  329,
      337,  336,  331,  338,  339,  326,  342,  342,  328,  344,
      347,  349,  354,  350,  353,  364,  360,  330,  350,  353,
      356,  360,  359,  363,  339,  347,  359,  345,  341,  344,

      354,  349,  340,  335,  356,  364,  334,  363,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  368,
      333,  368,  368,  368,  332,  368,  368,  368,  368,  368,
      369,  327,  369,  369,  324,  369,  369,  370,  323,  370,
      370,  320,  370,  370,  371,  319,  371,  318,  371,  371,
      371,  371,  316,  371,  371,  372,  315,  372,  372,  314,
      372,  305,  372,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  374,  303,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  375,  375,  300,  375,  376,
      376,  377,  377,  378,  298,  294,  293,  289,  285,  378,

      379,  281,  278,  277,  273,  265,  379,  380,  380,  381,
      381,  382,  382,  383,  383,  384,  384,  385,  385,  262,
      260,  250,  249,  245,  243,  240,  225,  224,  221,  205,
      198,  192,  189,  181,  172,  171,  164,  123,  115,  111,
      108,   99,   98,   97,   94,   91,   87,   79,   73,   63,
       42,   41,   33,   30,   20,   18,   17,   14,   13,   12,
        9,    5,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,

      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "lexer.l"

#line 8 "lexer.l"
    #include <iostream>
    #include <fstream>
    #include <string>
    #include <cstdlib>
    using namespace std;

    static string stringBuffer;

    void printLiteral(string type, string literal);
    void printType(string type);
    void printKeyword(string keyword);
    void printOperator(string op);
    void printIdentificator(string id);
    void printSeparator(string separator);

    string stripUnderscores(string s);
    string stripSuffix(string s, string chars);
    string normalizeInt(string s);
    string normalizeBinInt(string s);
    string normalizeHexInt(string s);
    string normalizeDouble(string s);

    string normalizeChar(string s);
    string decodeChar(string s);

#line 754 "lexer.cc"
/* хвост имени */
/* variable */
/*constructor identifier (класс, объект, тип) */
#line 758 "lexer.cc"

#define INITIAL 0
#define STRING 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
#define ECHO LexerOutput( yytext, yyleng )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
\
	if ( (int)(result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) LexerError( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
#define YY_DECL int yyFlexLexer::yylex()
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin.rdbuf(std::cin.rdbuf());

		if ( ! yyout )
			yyout.rdbuf(std::cout.rdbuf());

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 71 "lexer.l"


#line 894 "lexer.cc"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 367 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 366 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 73 "lexer.l"
{ /* пропуск пробелов */ }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 75 "lexer.l"
{ /* пропуск комментариев */ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 77 "lexer.l"
{ printType(YYText()); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 78 "lexer.l"
{ printType(YYText()); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 79 "lexer.l"
{ printType(YYText()); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 80 "lexer.l"
{ printType(YYText()); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 81 "lexer.l"
{ printType(YYText()); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 82 "lexer.l"
{ printType(YYText()); } /* аналог void */
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 84 "lexer.l"
{ printKeyword(YYText()); } /* Regular keywords */
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 85 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 86 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 87 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 88 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 89 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 90 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 91 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 92 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 93 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 94 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 95 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 96 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 97 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 98 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 99 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 100 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 101 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 102 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 103 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 104 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 105 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 106 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 107 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 108 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 109 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 110 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 111 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 112 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 113 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 114 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 115 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 116 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 117 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 118 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 119 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 120 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 121 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 122 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 123 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 124 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 126 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 127 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 128 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 129 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 130 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 131 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 132 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 133 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 134 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 136 "lexer.l"
{ printKeyword(YYText()); } /* Soft keywords */
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 137 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 138 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 139 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 140 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 141 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 142 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 143 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 144 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 145 "lexer.l"
{ printKeyword(YYText()); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 147 "lexer.l"
{ printLiteral("double", normalizeDouble(YYText())); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 149 "lexer.l"
{ printLiteral("int", normalizeInt(YYText())); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 150 "lexer.l"
{ printLiteral("int", normalizeBinInt(YYText())); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 151 "lexer.l"
{ printLiteral("int", normalizeHexInt(YYText())); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 153 "lexer.l"
{ printLiteral("char", normalizeChar(YYText())); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 155 "lexer.l"
{ printIdentificator(YYText()); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 156 "lexer.l"
{ printIdentificator(YYText()); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 158 "lexer.l"
{ printSeparator(YYText()); } /* Разделители */
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 159 "lexer.l"
{ printSeparator(YYText()); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 160 "lexer.l"
{ printSeparator(YYText()); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 161 "lexer.l"
{ printSeparator(YYText()); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 162 "lexer.l"
{ printSeparator(YYText()); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 163 "lexer.l"
{ printSeparator(YYText()); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 164 "lexer.l"
{ printSeparator(YYText()); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 165 "lexer.l"
{ printSeparator(YYText()); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 166 "lexer.l"
{ printSeparator(YYText()); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 168 "lexer.l"
{ printOperator(YYText()); } /* Операторы */
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 169 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 170 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 171 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 172 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 174 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 175 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 176 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 177 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 178 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 179 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 181 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 182 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 183 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 184 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 185 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 186 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 187 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 188 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 189 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 190 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 191 "lexer.l"
{ printOperator(YYText()); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 193 "lexer.l"
{ stringBuffer = ""; BEGIN(STRING); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 194 "lexer.l"
{ stringBuffer += YYText(); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 195 "lexer.l"
{ stringBuffer += '\n'; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 196 "lexer.l"
{ stringBuffer += '\\'; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 197 "lexer.l"
{ stringBuffer += '"'; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 199 "lexer.l"
{ stringBuffer += '\t'; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 200 "lexer.l"
{ stringBuffer += '\r'; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 201 "lexer.l"
{ stringBuffer += '\b'; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 202 "lexer.l"
{ stringBuffer += '\f'; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 204 "lexer.l"
{stringBuffer += decodeChar(YYText());}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 205 "lexer.l"
{stringBuffer += decodeChar(YYText());}
	YY_BREAK
case 118:
/* rule 118 can match eol */
YY_RULE_SETUP
#line 207 "lexer.l"
{  }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 209 "lexer.l"
{ printLiteral("string", stringBuffer);
                       BEGIN(INITIAL); }
	YY_BREAK
case 120:
/* rule 120 can match eol */
YY_RULE_SETUP
#line 212 "lexer.l"
{ cerr << "ERROR: EOL in string" << endl;
                       BEGIN(INITIAL); }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 215 "lexer.l"
{ cerr << "Unexpected char \'" << YYText()[0] << "\'" << endl; BEGIN(INITIAL);}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 217 "lexer.l"
ECHO;
	YY_BREAK
#line 1563 "lexer.cc"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STRING):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin.rdbuf();
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* The contents of this function are C++ specific, so the () macro is not used.
 * This constructor simply maintains backward compatibility.
 * DEPRECATED
 */
yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout ):
	yyin(arg_yyin ? arg_yyin->rdbuf() : std::cin.rdbuf()),
	yyout(arg_yyout ? arg_yyout->rdbuf() : std::cout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::yyFlexLexer( std::istream& arg_yyin, std::ostream& arg_yyout ):
	yyin(arg_yyin.rdbuf()),
	yyout(arg_yyout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::ctor_common()
{
	yy_c_buf_p = 0;
	yy_init = 0;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = NULL;

	yy_buffer_stack = NULL;
	yy_buffer_stack_top = 0;
	yy_buffer_stack_max = 0;

	yy_state_buf = 0;

}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::~yyFlexLexer()
{
	delete [] yy_state_buf;
	yyfree( yy_start_stack  );
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yyfree( yy_buffer_stack  );
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream& new_in, std::ostream& new_out )
{
	// was if( new_in )
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE  ) );

	// was if( new_out )
	yyout.rdbuf(new_out.rdbuf());
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream* new_in, std::ostream* new_out )
{
	if( ! new_in ) {
		new_in = &yyin;
	}

	if ( ! new_out ) {
		new_out = &yyout;
	}

	switch_streams(*new_in, *new_out);
}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
{
	if ( yyin.eof() || yyin.fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin.get( buf[0] );

	if ( yyin.eof() )
		return 0;

	if ( yyin.bad() )
		return -1;

	return 1;

#else
	(void) yyin.read( buf, max_size );

	if ( yyin.bad() )
		return -1;
	else
		return yyin.gcount();
#endif
}

void yyFlexLexer::LexerOutput( const char* buf, int size )
{
	(void) yyout.write( buf, size );
}

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
int yyFlexLexer::yy_get_next_buffer()
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    yy_state_type yyFlexLexer::yy_get_previous_state()
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 367 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 367 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 366);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT
    void yyFlexLexer::yyunput( int c, char* yy_bp)
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
#endif

    int yyFlexLexer::yyinput()
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyFlexLexer::yyrestart( std::istream& input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Delegate to the new version that takes an istream reference.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
void yyFlexLexer::yyrestart( std::istream* input_file )
{
	if( ! input_file ) {
		input_file = &yyin;
	}
	yyrestart( *input_file );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

    void yyFlexLexer::yy_load_buffer_state()
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin.rdbuf(YY_CURRENT_BUFFER_LVALUE->yy_input_file);
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream& file, int size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Delegate creation of buffers to the new version that takes an istream reference.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
	YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream* file, int size )
{
	return yy_create_buffer( *file, size );
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, std::istream& file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file.rdbuf();
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

	b->yy_is_interactive = 0;
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yyFlexLexer::yypush_buffer_state (YY_BUFFER_STATE new_buffer)
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yyFlexLexer::yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
void yyFlexLexer::yyensure_buffer_stack(void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

    void yyFlexLexer::yy_push_state( int _new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_size_t) (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc( new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc(
					(void *) (yy_start_stack), new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(_new_state);
}

    void yyFlexLexer::yy_pop_state()
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    int yyFlexLexer::yy_top_state()
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

void yyFlexLexer::LexerError( const char* msg )
{
    	std::cerr << msg << std::endl;
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 217 "lexer.l"


int main(int argc, char** argv) {
    if (argc < 2) {
        cerr << "Usage: " << argv[0] << " <file.scala>" << endl;
        return 1;
    }

    ifstream in(argv[1]);
    if (!in) {
        cerr << "Cannot open file: " << argv[1] << endl;
        return 1;
    }

    yyFlexLexer lexer(&in, &cout);
    lexer.yylex();

    return 0;
}

void printLiteral(string type, string literal) {
    cout << type << " literal: " << literal << endl;
}

void printType(string type) {
    cout << "type: " << type << endl;
}

void printKeyword(string keyword) {
    cout << "keyword: " << keyword << endl;
}

void printOperator(string op) {
    cout << "operator: " << op << endl;
}

void printIdentificator(string id) {
    cout << "id: " << id << endl;
}

void printSeparator(string separator) {
    cout << "separator: " << separator << endl;
}

string stripUnderscores(string s) {
    string result;
    result.reserve(s.size());
    for (char c : s) {
        if (c != '_') result += c;
    }
    return result;
}

string stripSuffix(string s, string chars) {
    if (s.empty()) return s;

    char last = s[s.size() - 1];
    for (char c : chars) {
        if (c == last) return s.substr(0, s.size() - 1);
    }
    return s;
}

string normalizeInt(string s) {
    string result = stripUnderscores(s);
    result = stripSuffix(result, "lL");

    int i = 0;
    while (i + 1 < (int)result.size() && result[i] == '0') i++;
    return result.substr(i);
}

string normalizeBinInt(string s) {
    string clean = stripUnderscores(s);

    bool isLong = false;
    if (!clean.empty()
        && (clean[clean.size() - 1] == 'l' || clean[clean.size() - 1] == 'L')) {
        clean = clean.substr(0, clean.size() - 1);
        isLong = true;
    }

    int start = 0;
    if (clean.size() >= 2
        && clean[0] == '0'
        && (clean[1] == 'b' || clean[1] == 'B')) {
        start = 2;
    }

    unsigned long long v = 0;
    for (int i = start; i < (int)clean.size(); i++) {
        char c = clean[i];
        if (c == '0' || c == '1') {
            v = (v << 1) | (unsigned long long)(c - '0');
        }
    }

    string result = to_string(v);
    if (isLong) result += "L";
    return result;
}

string normalizeHexInt(string s) {
    string clean = stripUnderscores(s);

    bool isLong = false;
    if (!clean.empty()
        && (clean[clean.size() - 1] == 'l' || clean[clean.size() - 1] == 'L')) {
        clean = clean.substr(0, clean.size() - 1);
        isLong = true;
    }

    int start = 0;
    if (clean.size() >= 2
        && clean[0] == '0'
        && (clean[1] == 'x' || clean[1] == 'X')) {
        start = 2;
    }

    unsigned long long v = 0;
    for (int i = start; i < (int)clean.size(); i++) {
        char c = clean[i];
        int d = -1;
        if (c >= '0' && c <= '9')      d = c - '0';
        else if (c >= 'a' && c <= 'f') d = c - 'a' + 10;
        else if (c >= 'A' && c <= 'F') d = c - 'A' + 10;
        if (d >= 0) v = v * 16 + (unsigned long long)d;
    }

    string result = to_string(v);
    if (isLong) result += "L";

    return result;
}

string normalizeDouble(string s) {
    string result = stripUnderscores(s);
    result = stripSuffix(result, "fFdD");

    bool hasDotOrExp = false;
    for (char c : result) {
        if (c == '.' || c == 'e' || c == 'E') {
            hasDotOrExp = true;
            break;
        }
    }

    if (!hasDotOrExp) result += ".0";

    return result;
}

string normalizeChar(string s) {
    // отрезаем обрамляющие '
    string inner = s.substr(1, s.size() - 2);

    return decodeChar(inner);
}

string decodeChar(string inner) {
    // одиночный символ — как есть
    if (inner.size() == 1) return inner;

    // \uXXXX -> попытаемся раскрыть, если печатаемый
    if (inner.size() == 6 && inner[0] == '\\' && inner[1] == 'u') {
        unsigned int code = 0;
        for (int i = 2; i < 6; i++) {
            char c = inner[i];
            int d = -1;
            if (c >= '0' && c <= '9')      d = c - '0';
            else if (c >= 'a' && c <= 'f') d = c - 'a' + 10;
            else if (c >= 'A' && c <= 'F') d = c - 'A' + 10;
            if (d < 0) return inner;
            code = code * 16 + d;
        }
        if (code >= 32 && code < 127 && code != '\'' && code != '\\') {
            return string(1, (char)code);
        }
        return inner;
    }

    // \NNN — восьмеричный escape
    if (inner.size() >= 2 && inner[0] == '\\'
        && inner[1] >= '0' && inner[1] <= '7') {
        unsigned int code = 0;
        int digits = 0;
        for (int i = 1; i < (int)inner.size() && digits < 3; i++) {
            char c = inner[i];
            if (c < '0' || c > '7') break;
            code = code * 8 + (c - '0');
            digits++;
        }
        if (code >= 32 && code < 127 && code != '\'' && code != '\\') {
            return string(1, (char)code);
        }
        return inner;   // непечатаемый — оставляем \NNN
    }

    // остальные escape (\n, \t, \', \\ и т.п.) — как есть
    return inner;
}
